services:
  app:
    image: ghcr.io/fresel/cf-weather-data:latest
    container_name: cf-weather-data
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
