spring:
  application:
    name: cf-weather-api
info:
  app:
    name: @project.artifactId@
    version: @project.version@
  description: CF Weather Data Backend API
  title: CF Weather Data API
external:
  api:
    weather:
      base-url: https://api.openweathermap.org/data/2.5
      api-key: ${WEATHER_API_KEY}