' Weather API Overview
' Generated with C4-PlantUML
@startuml overview
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!include $ICONURL/common.puml
!include $ICONURL/devicons2/spring_original.puml
!include $ICONURL/devicons2/java.puml
!include $ICONURL/devicons2/json.puml
!include $ICONURL/font-awesome-5/users.puml

Person(user, "Weather enthusiast", "A user of the Weather API", $sprite="users")
System_Boundary(weatherSystem, "CF Weather Data") {
    Container(weatherApi, "API", "Spring Boot Application", "Handles the business logic for weather data", $sprite="spring_original")
}
System_Ext(weatherDataProvider, "Weather Data Provider", "External Service", "Provides weather data", $sprite="json", $link="https://openweathermap.org")
System_Ext(geoLocationService, "Geo-Location Service", "External Service", "Provides geo-location data", $sprite="json", $link="http://openweathermap.org")
Rel(user, weatherApi, "Uses", "HTTPS")
Rel(weatherApi, weatherDataProvider, "Fetches data from", "HTTPS", $link="https://api.openweathermap.org/data/2.5/weather")
Rel(weatherApi, geoLocationService, "Fetches geo-location data from", "HTTP", $link="http://api.openweathermap.org/geo/1.0/reverse")

SHOW_LEGEND()
@enduml