@api={{apiBaseUrl}}

@longitude=18.063240
@latitude=59.334591

### Request current weather
GET {{api}}?lat={{latitude}}&lon={{longitude}}&type=current
Accept: application/json

?? status == 200

### Request weather forecast
GET {{api}}?lat={{latitude}}&lon={{longitude}}&type=forecast
Accept: application/json

?? status == 200

### Request with invalid type
GET {{api}}?lat={{latitude}}&lon={{longitude}}&type=invalid
Accept: application/json

?? status == 400

### Request with missing parameters
GET {{api}}?lat={{latitude}}&type=current
Accept: application/json

?? status == 400